# -*- mode: ruby -*-
# vi: set ft=ruby :

machines = {
  "master" => {"memory" => "512", "cpu" => "1", "ip" => "10", "image" => "generic/ubuntu1604"},
  "node01" => {"memory" => "512", "cpu" => "1", "ip" => "11", "image" => "generic/ubuntu1604"},
  "node02" => {"memory" => "512", "cpu" => "1", "ip" => "12", "image" => "generic/ubuntu1604"},
  "node03" => {"memory" => "512", "cpu" => "1", "ip" => "13", "image" => "generic/ubuntu1604"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    # config.vm.synced_folder "./", "/vagrant"
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "192.168.20.#{conf["ip"]}"
      
      machine.vm.provider "libvirt" do |lt|
        lt.memory = "#{conf["memory"]}"
        lt.cpus = "#{conf["cpu"]}"
      end
      
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = "#{conf["memory"]}"
        vb.cpus = "#{conf["cpu"]}"
      end

      machine.vm.provision "shell", path: "install-docker.sh"

      if "#{name}" == "master"
        machine.vm.provision "shell", path: "configure-master.sh"
      else
        machine.vm.provision "shell", path: "configure-worker.sh"
      end
    end
  end
end
